version: '3'

services:

  wait_app:
    image: dadarek/wait-for-dependencies
    depends_on:
      - reverse-proxy
    command: front:8080
  cypress:
    # the Docker image to use from https://github.com/cypress-io/cypress-docker-images
    image: "cypress/included:3.8.3"
    depends_on:
      - reverse-proxy
    environment:
      # pass base url to test pointing at the web application
      - CYPRESS_baseUrl=http://front:8080
    working_dir: /e2e
    volumes:
      - ./e2e/:/e2e